title: Kickstart Scheme Theory
author: Broccoli Topology
email: taricpinkfriend@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I like sushi.

# social links
twitter_username: taricpinkfriend # DO NOT include the @ character, or else the build will fail!
github_username: taricpinkfriend # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
